export const SET_CHARACTERS = "SET_CHARACTERS";
export const START_CHARACTERS_LOADING = "START_CHARACTERS_LOADING";
export const END_CHARACTERS_LOADING = "END_CHARACTERS_LOADING";
export const SET_PAGE = "SET_PAGE";
